### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openitcockpit-agent-go#77]
**Agent Mode**:
* [] Pull Model (openITCOCKPIT Server request data from Agent)
* [x] Push Model (Agent send data to openITCOCKPIT)

**Versions**
* openITCOKPIT Server Version: 4.5.5
* openITCOCKPIT Monitoring Agent Version: 3.0.10-1

**Operating system**
```
NAME="openSUSE Leap"
VERSION="15.1"
```

* Do you use an HTTP proxy? -> `NO`
* Are you using Auto-TLS, HTTPS or HTTP? -> `NO`
* Used CPU architecture: i386, amd64, arm64 or armhf -> `amd64`

**Describe the bug**
Push agent can't connect: `level=error msg="Push Client: could not send state to server:  Invalid credentials or host not found"`

**To Reproduce**
1. Install fresh clean agent on client with zypper
2. Create new host with `openITCOCKPIT Agent - Push` template
3. Go to agent setup and generate new push config with api key
4. Apply config and restart agent service
5. See error log

**Expected behavior**
Agent should connect to server

**Additional context**
Connection to oitc server should work. Agent system has internet access.
Also tested DNS resolve with nslokkup

**Comment by nook24** [comment]
This is probably a normal / wanted behavior.  The error message `Invalid credentials or host not found` has two meanings.

1. `Invalid credentials`
The agent can not send data to the openITCOCKPIT server, because of:
  - Wrong API key in the configuration of the Agent
  - The agent got removed from openITCOCKPIT (openITCOCKPIT Agent -> Agents Overview)
  - Agent got copied from another system. Delete the `auth.json` on the Agent and remove the Agent from  Agents Overview
https://github.com/it-novum/openitcockpit-agent-go/wiki/Debugging#paths

2. `Host not found`
This part of the error message just says, that no host is assigned to the openITCOCKPIT Monitoring Agent yet. To verify this, open the Agents Overview and check if the agent is pushing data to openITCOCKPIT. If the Agent is pussing data everything works as expected but the data is not used.

To start monitoring, assign the Agent to an host.

**Comment by some-git-user** [comment]
@nook24 thank you for your feedback.
To be honest, I would have expected a different message, if I only have to assign the Agent to an host.
Back when I created this issue, there was no agent available at the "Available Agents" drop down menu. So I assumed an problem. But now I rechecked the drop down and yes the agent appeared.
